--Q1 What is the total revenue generated by male vs female customers?
SELECT
	GENDER,
	SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM
	CUSTOMER
GROUP BY
	GENDER
ORDER BY
	SUM(PURCHASE_AMOUNT) DESC;

--Q2 Which customer used a discount but still spent more than the average purchase?
SELECT
	CUSTOMER_ID,
	PURCHASE_AMOUNT
FROM
	CUSTOMER
WHERE
	DISCOUNT_APPLIED = 'Yes'
	AND PURCHASE_AMOUNT > (
		SELECT
			AVG(PURCHASE_AMOUNT)
		FROM
			CUSTOMER
	);

--Q3 which are the top 5 products with the highest average review rating?
SELECT
	ITEM_PURCHASED,
	ROUND(AVG(REVIEW_RATING::NUMERIC), 2) AS AVERAGE_RATING
FROM
	CUSTOMER
GROUP BY
	ITEM_PURCHASED
ORDER BY
	AVG(REVIEW_RATING) DESC
LIMIT
	5;

--Q4 Compare the average Purchase Amounts between Standard and Express Shipping?
SELECT
	SHIPPING_TYPE,
	ROUND(AVG(PURCHASE_AMOUNT), 2) AS AVG_AMMOUNT
FROM
	CUSTOMER
GROUP BY
	SHIPPING_TYPE
HAVING
	SHIPPING_TYPE IN ('Standard', 'Express')
	--Q5 Do subscribed customer spends more? Compare average spend and total revenue between subscribed and non subscribed customer?
SELECT
	COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMER,
	SUBSCRIPTION_STATUS,
	SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE,
	ROUND(AVG(PURCHASE_AMOUNT), 2) AS AVG_REVENUE
FROM
	CUSTOMER
GROUP BY
	SUBSCRIPTION_STATUS
	--Q6 Which 5 products have the highest percentage of purchase with discounts applied?
SELECT
	ITEM_PURCHASED,
	ROUND(
		100 * SUM(
			CASE
				WHEN DISCOUNT_APPLIED = 'Yes' THEN 1
				ELSE 0
			END
		) / COUNT(*),
		2
	) AS DISCOUNT_RATE
FROM
	CUSTOMER
GROUP BY
	ITEM_PURCHASED
ORDER BY
	DISCOUNT_RATE DESC
LIMIT
	5;

--Q7 Segment customers into New, Returning and loyal based on their total number
--of previous purchases and show the count of each segment
SELECT
	CUSTOMER_SEGMENT,
	COUNT(*) AS TOTAL_CUSTOMER
FROM
	(
		SELECT
			CUSTOMER_ID,
			PREVIOUS_PURCHASES,
			CASE
				WHEN PREVIOUS_PURCHASES = 1 THEN 'New'
				WHEN PREVIOUS_PURCHASES BETWEEN 2 AND 10  THEN 'Returning'
				ELSE 'Loyal'
			END AS CUSTOMER_SEGMENT
		FROM
			CUSTOMER
	)
GROUP BY
	CUSTOMER_SEGMENT
ORDER BY
	TOTAL_CUSTOMER;

--Q8 What are ther top 3 most purchased products within each category
WITH
	ITEM_COUNT AS (
		SELECT
			CATEGORY,
			ITEM_PURCHASED,
			COUNT(CUSTOMER_ID) AS TOTAL_ORDER,
			ROW_NUMBER() OVER (
				PARTITION BY
					CATEGORY
				ORDER BY
					COUNT(CUSTOMER_ID)
			) AS MOST_PURCHASED
		FROM
			CUSTOMER
		GROUP BY
			CATEGORY,
			ITEM_PURCHASED
	)
SELECT
	CATEGORY,
	ITEM_PURCHASED,
	TOTAL_ORDER
FROM
	ITEM_COUNT
WHERE
	MOST_PURCHASED <= 3;

--Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
	SUBSCRIPTION_STATUS,
	COUNT(CUSTOMER_ID) AS REPEATED_CUSTOMER
FROM
	CUSTOMER
WHERE
	PREVIOUS_PURCHASES > 5
GROUP BY
	SUBSCRIPTION_STATUS
	--Q10 what is revenue contribution of each age group?
SELECT
	AGE_GROUP,
	SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM
	CUSTOMER
GROUP BY
	AGE_GROUP
ORDER BY
	TOTAL_REVENUE